name: Update CSIS RSS

on:
  schedule:
    # runs hourly (GitHub uses UTC)
    - cron:  '0 * * * *'
  workflow_dispatch: # allow manual trigger

jobs:
  build-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RSS generator
        run: |
          python rss_generator.py

      - name: Show generated file
        run: |
          echo "----- rss.xml -----"
          sed -n '1,200p' rss.xml || true

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if git status --porcelain | grep rss.xml; then
            git add rss.xml
            git commit -m "Automated: update rss.xml ($(date -u +'%Y-%m-%d %H:%M:%S UTC'))"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit."
          fi
        env:
          # GITHUB_TOKEN is provided automatically; actions/checkout@v4 supports it by default,
          # but we include it in env for clarity if pushing via HTTPS is required.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
